#Respuestas por defecto
# -*- coding: latin-1 -*-
opciones = {
    "users": {"Pablo Marinozi","Facundo Bromberg","Diego Sebastián Pérez","Carlos Ariel Díaz","Wenceslao Villegas","Juan Manuel López Correa"},
    "inclusion_criteria": ("El estudio utiliza algún proceso de extracción de información automatizado sobre imágenes de cualquier región del espectro electromagnético en alguna de sus etapas.",
                           "El estudio se enfoca en la medición de variables de interés vitícola indistintamente de la ubicación geográfica y el sistema de conducción de los viñedos y del varietal y propósito de comercialización de las uvas."),
    "exclusion_criteria": ("El estudio utiliza como entrada imágenes en las que la resolución de un pixel es mayor a un metro.",
                            "El algoritmo opera sobre información electromagnética que no viene en forma de imagen (entiéndase representación visual bidimensional a partir de una matriz numérica) ",
                            "El paper está orientado a automatismo de la gestión, no a medición de variables.",
                            "El estudio no está escrito en Inglés.",
                            "La publicación del estudio no se sometió a un proceso de revisión por pares."),
    "dataset_format_list" : {"Fotografí­as Aisladas", "Fotogramas de videos"},
    "viticultural_objects_list" : {"Bayas (Racimos)", "Bayas (Granos)", "Hojas (Individuales)", "Hojas (Canopia)",
                                 "Yemas", "Tronco"},
    "data_capture_conditions_list" : {"Condiciones naturales de campo", "Condiciones controladas en el campo",
                              "Condiciones controladas en el laboratorio"}, 
    "electromagnetic_spectrum_list" : {"Espectro Visible", "Infrarrojo", "Multiespectral", "Hiperespectral"},
    "camera_types_list" : {"Monocular", "Stereo", "Profundidad"},
    "visual_tasks_list" : {
        "Segmentación 2D de objetos de interés.",
        "Detección 2D de objetos de interés (bounding box)",
        "Detección 2D de objetos de interés (centro de masa)",
        "Detección 2D de objetos de interés (máscara del objeto 2D)",
        "Detección 3D de objetos de interés (bounding box)",
        "Detección 3D de objetos de interés (centro de masa)",
        "Detección 3D de objetos de interés (máscara del objeto 3D)",
        "Reconstrucción 3D de objetos de interés.",
        "Identificación/Diferenciación 2D/3D de instancias de objeto de interés.",
        "Tracking de objetos de interés"},
    "visual_features_types": {"Handcrafted", "Latent", "Deep"},
    "visual_features_handcrafted_list" : {
        "Máscaras de Textura de Laws",
        "Filtros de Gabor",
        "SGF (Steerable Gaussian Filter)",
        "Histogramas de color",
        "CCV (Color Coherence Vector)",
        "Histogramas de Momentos de Color",
        "CC (Color Correlogram)",
        "GCM (Gray-level Co-occurrence Matrix)",
        "Contexto de Forma (Shape Context)",
        "Momentos Geométricos",
        "HOG (Histogram of Oriented Gradients)",
        "SIFT (Scale-Invariant Feature Transform)",
        "SURF (Speeded-Up Robust Features)",
        "ORB (Oriented FAST and rotated BRIEF)"},
    "visual_features_latent_list" : {
        "PCA (Principal Component Analysis)",
        "Kernel PCA (Kernel Principal Component Analysis)",
        "MDS (Multidimensional Scaling",
        "Isomap",
        "Laplacian Eigenmaps"},
    "visual_features_deep_list" : {
        "AlexNet",
        "VGG group",
        "LeNet",
        "GoogleNet",
        "Inception"},
    "algorithms_list" : {"SVM (Support Vector Machines)", "Multilayer Perceptron"},
    "viticultural_variable_list" : {
        "Flower number",
        "Berry maturity",
        "Berry number",
        "Berry weight" ,
        "Berry size",
        "Berry volume",
        "Cluster compactness (density)",
        "Cluster morphology (length, width, size, elongation)",
        "Cluster volume",
        "Cluster number",
        "Cluster weight",
        "Yield",
        "Leaf Area"},
    "viticultural_aspects_list" : {
        "Información cuantitativa de la producción",
        "Calidad de la producción",
        "Estado general del viñedo"},
    "research_goal_list" : {
        "Disminuir costos en procesos productivos.",
        "Reducir la laboriosidad de las tareas manuales llevadas adelante por el personal.",
        "Posibilitar las mediciones actuales en escala masiva/mayor granularidad espacio-temporal.",
        "Posibilitar la medición de variables más complejas/sutiles que las actuales."},
    "practical_contibution_list" : {
        "Producto terminado de código abierto.",
        "Producto terminado privativo.",
        "Implementación de código abierto de los modelos de CV",
        "Ninguna de las anteriores."}
}